name: dllm-dev
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - anaconda::jupyter
  - nvidia/label/cuda-12.4.1::cuda-nvcc
  - python=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pip
  - pip:
      - datasets
      - einops
      - fire
      - hydra-core
      - ipdb
      - magic-wormhole
      - mosaicml
      - mosaicml-streaming
      - pre-commit
      - sentencepiece
      - ruff
      - transformers
      - wandb
