name: e2d2-env
channels:
  - pytorch
  - anaconda
  - nvidia
  - defaults
dependencies:
  - anaconda::jupyter
  - nvidia/label/cuda-12.4.1::cuda-nvcc
  - python=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pip
  - pip:
      - accelerate==1.11.0
      - datasets==4.2.0
      - einops==0.8.1
      - fire==0.7.1
      - hydra-core==1.3.2
      - ipdb
      - lm-eval==0.4.9
      - magic-wormhole
      - mosaicml==0.32.1
      - mosaicml-streaming==0.13.0
      - pre-commit
      - sentencepiece==0.2.1
      - ruff
      - transformers==4.52.4
      - wandb==0.22.2
