_target_: src.backbone.bd3lm_encoder_decoder.BD3LMEncoderDecoder
pretrained_model_name_or_path: ${pretrained_model_name_or_path}
keep_every_n_encoder_layers: 1
max_length: ${model.config.length}
attn_backend: ${model.config.attn_backend}
use_encoder_causal_mask: false
keep_top_n_encoder_layers: ???
