wmt_stop_string_criteria:
  _target_: transformers.generation.StopStringCriteria
  tokenizer: ${tokenizer}
  stop_strings:
    - '<|im_end|>'
    - '<|endoftext|>'
    - '.'  # Only use first generated sentence (test set only contains single sentence)
