defaults:
  - mdlm@_here_
  - _self_

_target_: src.denoiser.diffusion.BD3LM
config:
  _target_: src.denoiser.diffusion.BD3LMConfig
  block_size: ${block_size}
  eval_block_size: ${block_size}
  backbone_is_decoder_only: true  # true for BD3LM, false for E2D2
  shift_logits: false
