# Not actually used, just serves as a placeholder to put `_target_` as first key
_target_: src.denoiser.Denoiser
config:
  _target_: src.denoiser.DenoiserConfig
  # Prevents backbone and noise from being instantiated when `hydra.utils.instantiate`
  # is called.
  # These should be instantiated by in model init.
  _recursive_: false
  length: ???
  # OmegaConf resolver creates the dictionary that contains tokenizer config params
  tokenization_config: ${oc.create:${make_tokenization_config:${tokenizer}}}
