_target_: src.sampler.AncestralSampler
config:
  _target_: src.sampler.SamplerConfig
  num_samples: 1
  batch_size: 1
  max_length: 512
  num_steps: 1000
  min_t: 1e-5
  disable_cache: false
  block_size: ${model.config.length}
  top_p: 0.85
  pad_context: false
  greedy: false
  first_hitting: true
  low_confidence_remasking: true
  kv_caching: true
  shift_logits: ${model.config.shift_logits}
