_target_: src.datasets.tokenize_on_demand.CNNDailyMailDataset
split: "train"
max_length: ${model.config.length}
dataset_path: "abisee/cnn_dailymail"
padding: false
add_special_tokens: true
source_prompt_text: null
target_prompt_text: "Summary: "
truncate: true
