_target_: src.datasets.streaming_dataset_hf.StreamingHFDataset
name: HuggingFaceFW/fineweb-edu
split: train
max_length: ${model.config.length}
shuffle_buffer_size: null
seed: ${seed}
padding: false
take_size: 0
