#file: noinspection LongLine
_target_: src.datasets.tokenize_on_demand.GSM8KDataset
split: "train"
max_length: ${model.config.length}
dataset_path: "openai/gsm8k"
config_name: "main"
padding: false
add_special_tokens: true
num_shot: 0
source_key: "question"
target_key: "answer"
source_prompt_text: "Please reason step by step, and put your final answer within $\\boxed{}$. "
target_prompt_text: "Answer: "
