_target_: src.datasets.tokenize_on_demand.WMTDataset
split: "train"
max_length: ${model.config.length}
dataset_path: "wmt/wmt14"
padding: false
add_special_tokens: true
source_prompt_text: null
target_prompt_text: null
