fsdp:
  sharding_strategy: "FULL_SHARD"
  cpu_offload: null
  mixed_precision:
    param_dtype: ${composer.trainer.precision}
    reduce_dtype: ${composer.trainer.precision}
    buffer_dtype: ${composer.trainer.precision}
  backward_prefetch: "BACKWARD_POST"
  activation_checkpointing: false
  activation_cpu_offload: false
  verbose: true
